### ISSUE TITLE
No such file or directory: '/dev/shm/_tmp_2way_v.txt.out' when run "python _2c_generate_fm_features.py" in "_0_run_me.sh"

### ISSUE THREAD

**Issue by SeekPoint** [owenzhang/kaggle-avazu#3]
while start  **_0_run_me.sh,**
 It report such error when run **"python _2c_generate_fm_features.py"**

t0tv_mx loaded with shape (10999998, 43)
t0 loaded with shape (10999998, 40)
22 all_withid
to write data files ...
/media/rzai/ai_data/prj/kaggle-2014-criteo/solvers/libffm-1.13/ffm-train -t 4 -s 8 -l 1e-5 /dev/shm/_tmp_2way_v.txt /dev/shm/_tmp_2way_t.txt
load results ...
Traceback (most recent call last):
  File "_2c_generate_fm_features.py", line 78, in <module>
    fm_predv = pd.read_csv(open(path1 + '_tmp_2way_v.txt.out', 'r'), header=None).ix[:,0].values
IOError: [Errno 2] No such file or directory: '/dev/shm/_tmp_2way_v.txt.out'

**Comment by SeekPoint** [comment]
I try to fixed it by change _tmp_2way_v.txt.out to _tmp_2way_v.txt

but got:

============================================================
23 fm_5vars
to write data files ...
/media/rzai/ai_data/prj/kaggle-2014-criteo/solvers/libffm-1.13/ffm-train -t 4 -s 8 -l 1e-5 /dev/shm/_tmp_2way_v.txt /dev/shm/_tmp_2way_t.txt
load results ...
--- gini_norm: 1.0
============================================================
24 all_withid
to write data files ...
/media/rzai/ai_data/prj/kaggle-2014-criteo/solvers/libffm-1.13/ffm-train -t 4 -s 8 -l 1e-5 /dev/shm/_tmp_2way_v.txt /dev/shm/_tmp_2way_t.txt
iter   tr_logloss
   1         -nan
   2         -nan
   3         -nan
   4         -nan
load results ...
Traceback (most recent call last):
  File "_2c_generate_fm_features.py", line 78, in <module>
    fm_predv = pd.read_csv(open(path1 + '_tmp_2way_v.txt', 'r'), header=None).ix[:,0].values
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 470, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 246, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 562, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 699, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1066, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 512, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4804)
ValueError: No columns to parse from file

**Comment by liuyiyiyiyi** [comment]
How doyou solve the problem?
